// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcqpgfyebbxdjmzarnfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjcXBnZnllYmJ4ZGptemFybmZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NzgwNDMsImV4cCI6MjA1MjQ1NDA0M30.CbetDcMKTTJAOJa19zrj48w3JIfLIezPjQKIn9n803I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});